# Generated by Django 5.2.16 on 2026-08-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100, verbose_name='اسم عروس')),
                ('groom_name', models.CharField(max_length=100, verbose_name='اسم داماد')),
                ('wedding_date', models.DateTimeField(verbose_name='تاریخ و ساعت عروسی')),
                ('venue', models.CharField(max_length=255, verbose_name='محل برگزاری')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('love_story', models.TextField(blank=True, verbose_name='داستان عشق')),
                ('photo_main', models.ImageField(blank=True, upload_to='invitation/', verbose_name='عکس اصلی')),
                ('map_embed', models.TextField(blank=True, help_text='لینک iframe گوگل مپ را اینجا بچسبانید', verbose_name='کد نقشه گوگل (iframe)')),
            ],
            options={
                'verbose_name': 'دعوتنامه',
                'verbose_name_plural': 'دعوتنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شما')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('attending', models.BooleanField(default=True, verbose_name='شرکت می\u200cکنم')),
                ('message', models.TextField(blank=True, verbose_name='پیام تبریک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitation.invitation')),
            ],
        ),
    ]
