# Generated by Django 5.2.16 on 2026-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='video_url',
            field=models.FileField(blank=True, help_text='فرمت mp4 پیشنهاد می\u200cشود', null=True, upload_to='videos/', verbose_name='ویدئوی اینترو'),
        ),
    ]
