# Generated by Django 6.0.5 on 2026-08-09 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitation_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['-created_at'], 'verbose_name': 'پاسخ حضور', 'verbose_name_plural': 'پاسخ\u200cهای حضور'},
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='love_story',
            new_name='story_text',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='address',
            new_name='venue_address',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='map_embed',
            new_name='venue_map_embed',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='venue',
            new_name='venue_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='video_url',
        ),
        migrations.AddField(
            model_name='invitation',
            name='background_music',
            field=models.FileField(blank=True, help_text='فرمت mp3 پیشنهاد می\u200cشود', null=True, upload_to='invitation/music/', verbose_name='موزیک پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_parents',
            field=models.CharField(blank=True, help_text='مثلاً: آقای احمدی و خانم محمدی', max_length=150, verbose_name='نام پدر و مادر عروس'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_photo',
            field=models.ImageField(blank=True, upload_to='invitation/couple/', verbose_name='عکس عروس'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='gift_message',
            field=models.TextField(blank=True, help_text='پیامی که زیر کارت خراش\u200cدار نمایش داده می\u200cشود', verbose_name='پیام هدیه / کارت خراش\u200cدار'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_parents',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام پدر و مادر داماد'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_photo',
            field=models.ImageField(blank=True, upload_to='invitation/couple/', verbose_name='عکس داماد'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='intro_video',
            field=models.FileField(blank=True, help_text='فرمت mp4 پیشنهاد می\u200cشود', null=True, upload_to='invitation/videos/', verbose_name='ویدئوی اینترو'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='guests_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد همراهان'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='invitation/', verbose_name='عکس اصلی (هدر)'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitation.invitation', verbose_name='دعوتنامه'),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invitation/gallery/', verbose_name='عکس')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='توضیح کوتاه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='invitation.invitation', verbose_name='دعوتنامه')),
            ],
            options={
                'verbose_name': 'عکس گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvitationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: مراسم عقد', max_length=100, verbose_name='عنوان مراسم')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ و ساعت')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='محل برگزاری')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitation.invitation', verbose_name='دعوتنامه')),
            ],
            options={
                'verbose_name': 'برنامه مراسم',
                'verbose_name_plural': 'برنامه\u200cهای مراسم',
                'ordering': ['order', 'date_time'],
            },
        ),
    ]
