# Generated by Django 5.2.16 on 2026-08-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_rsvp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationevent',
            name='rsvp_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس RSVP'),
        ),
    ]
