# Generated by Django 5.2.16 on 2026-08-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_invitationevent_rsvp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationevent',
            name='rsvp_url',
        ),
        migrations.AddField(
            model_name='invitation',
            name='rsvp_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس RSVP'),
        ),
    ]
