# Generated by Django 5.2.16 on 2026-08-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_remove_invitationevent_rsvp_url_invitation_rsvp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='rsvp_url',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='آدرس RSVP'),
        ),
    ]
